### ISSUE TITLE
"TypeError Cannot read properties of undefined (reading 'end')"

### ISSUE THREAD

**Issue by atonsis** [jonnyboyC/kos-language-server#208]
VSCode is constantly showing the output screen with the above error message nested in the following:

Node.js v20.14.0
[Info  - 7:43:45 PM] Connection to server got closed. Server will restart.
[KLS Server(22384)] Started and initialize received.
[Warn  - 7:43:45 PM] TypeError Cannot read properties of undefined (reading 'end')
[Warn  - 7:43:45 PM] TypeError: Cannot read properties of undefined (reading 'end')
    at get end (c:\Users\<userRedacted>\.vscode\extensions\johnchabot.kos-vscode-1.1.4\server\dist\server.js:1:64754)
    at L.toLocation (c:\Users\<userRedacted>\.vscode\extensions\johnchabot.kos-vscode-1.1.4\server\dist\server.js:1:98327)
    at _.<anonymous> (c:\Users\<userRedacted>\.vscode\extensions\johnchabot.kos-vscode-1.1.4\server\dist\server.js:1:292212)
    at Generator.next (<anonymous>)
    at c:\Users\<userRedacted>\.vscode\extensions\johnchabot.kos-vscode-1.1.4\server\dist\server.js:1:283606
    at new Promise (<anonymous>)
    at n (c:\Users\<userRedacted>\.vscode\extensions\johnchabot.kos-vscode-1.1.4\server\dist\server.js:1:283351)
    at _.loadDocuments (c:\Users\<userRedacted>\.vscode\extensions\johnchabot.kos-vscode-1.1.4\server\dist\server.js:1:292047)
    at _.<anonymous> (c:\Users\<userRedacted>\.vscode\extensions\johnchabot.kos-vscode-1.1.4\server\dist\server.js:1:291373)
    at Generator.next (<anonymous>)

**Comment by Spartacus4297** [comment]
I am having the same issue. been ongoing since June or July

**Comment by jonnyboyC** [comment]
Hello! Sorry this project has been a bit mothballed. I have some time in the next few weeks to sort this out. Likely I'll just need to update a _lot_ of the libraries here to get things up to date with more modern vscode. I'll report back when I've had some time to look into this.
